---
  name: Release Charts

  on:
    push:
      branches:
        - main
      paths:
        - 'helm/**'

  jobs:
    dispatch-release:
      permissions:
        contents: write
      runs-on: ubuntu-latest
      steps:
        - name: Dispatch charts-release workflow
          uses: peter-evans/repository-dispatch@v3
          with:
            token: ${{ secrets.CHARTS_RELEASE_TOKEN }}
            repository: nasjonalarkivet/charts-release
            event-type: helm_release
            client-payload: >-
              {"repo":"${{ github.repository }}","ref":"${{ github.sha }}"}
